//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiToanGioTanHoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LichHoc
    {
        [Display(Name = "Mã Lịch Học")]
        public int MaLichHoc { get; set; }
        [Required]
        [Display(Name = "Mã Lớp Học Phần")]
        public string MaLHP { get; set; }
        [Required]
        [Display(Name = "Mã Phòng")]
        public int MaPhong { get; set; }
        [Required]
        [Display(Name = "Ngày Học")]
        public System.DateTime NgayHoc { get; set; }
        [Required]
        [Display(Name = "Tiết Bắt Đầu")]
        public int TietBatDau { get; set; }
        [Required]
        [Display(Name = "Tiết Kết Thúc")]
        public int TietKetThuc { get; set; }
        [Display(Name = "Giờ Tan Học")]
        public Nullable<System.TimeSpan> GioTanHoc { get; set; }

        public virtual LopHocPhan LopHocPhan { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
    }
}
